[xml]$data = Get-Content .\ad_hc_int.vxops.se.xml

$domain = $data.HealthcheckData.DomainFQDN
$reportdate = $data.HealthcheckData.GenerationDate

$globalScore = $data.HealthcheckData.GlobalScore
$StaleScore = $data.HealthcheckData.StaleObjectsScore
$privilegedScore = $data.HealthcheckData.PrivilegiedGroupScore
$trustscore = $data.HealthcheckData.TrustScore
$AnomalyScore = $data.HealthcheckData.AnomalyScore

# Import PSWriteHTML module
Import-Module PSWriteHTML

# Create PSCustomObjects from XML data
$healthcheckData = $data.SelectNodes("//HealthcheckRiskRule") | ForEach-Object {
    # Create new PSCustomObject for each node
    [PSCustomObject]@{
        Points = $_.Points
        Category = $_.Category
        Model = $_.Model
        Rationale = $_.Rationale
    }
} 

# Calculate summary statistics
$totalPoints = ($healthcheckData | Measure-Object -Property Points -Sum).Sum
$averagePoints = ($healthcheckData | Measure-Object -Property Points -Average).Average
$categoryCount = $healthcheckData | Group-Object Category | Select-Object Name, Count

$currentDateTime = "2025-04-10 09:00:04"
$currentUser = "DambergC"

New-HTML -TitleText "Healthcheck Risk Rules Report" -Online -FilePath "HealthcheckReport.html" {
   
    
    New-HTMLHeader {
        New-HTMLText -Text "Healthcheck Risk Rules Analysis - $domain" -Color '#990AE3' -Alignment center -FontSize 40
        
    }
    
    New-HTMLSection -HeaderText 'GlobalScore' -HeaderBackGroundColor '#990AE3' -HeaderTextColor White -HeaderTextSize 40 -HeaderTextAlignment center {
 
            New-HTMLPanel {
            New-HTMLText -Text "$globalScore" -Color '#990AE3' -Alignment center -FontSize 155 -FontWeight bold
            New-HTMLText -Text "/100" -Color '#990AE3' -Alignment center -FontSize 36
        }
    
    }


    New-HTMLSection -HeaderBackGroundColor '#990AE3' {

                New-HTMLPanel {
                New-HTMLText -Text 'Stale' -Color '#990AE3' -Alignment center -FontSize 40
            New-HTMLText -Text "$StaleScore" -Color '#990AE3' -Alignment center -FontSize 72 -FontWeight bold
            New-HTMLText -Text "/100" -Color '#990AE3' -Alignment center -FontSize 36
        }
                        New-HTMLPanel {
                        New-HTMLText -Text 'Privileged' -Color '#990AE3' -Alignment center -FontSize 40
            New-HTMLText -Text "$privilegedScore" -Color '#990AE3' -Alignment center -FontSize 72 -FontWeight bold
            New-HTMLText -Text "/100" -Color '#990AE3' -Alignment center -FontSize 36
        }
                        New-HTMLPanel {
                        New-HTMLText -Text 'Trust' -Color '#990AE3' -Alignment center -FontSize 40
            New-HTMLText -Text "$trustscore" -Color '#990AE3' -Alignment center -FontSize 72 -FontWeight bold
            New-HTMLText -Text "/100" -Color '#990AE3' -Alignment center -FontSize 36
        }
                                New-HTMLPanel {
                                New-HTMLText -Text 'Anomaly' -Color '#990AE3' -Alignment center -FontSize 40
            New-HTMLText -Text "$AnomalyScore" -Color '#990AE3' -Alignment center -FontSize 72 -FontWeight bold
            New-HTMLText -Text "/100" -Color '#990AE3' -Alignment center -FontSize 36
        }
    }

    New-HTMLSection -HeaderBackGroundColor '#990AE3' -HeaderText "Detailed Risk Rules" -HeaderTextSize 40 {
        New-HTMLTable -DataTable $healthcheckData -HideFooter -HideButtons -DisableSearch -PagingStyle full{
            New-TableHeader -Color White -BackgroundColor '#0066cc'
        } -SearchBuilder -FixedHeader -PagingLength $healthcheckData.Count -Buttons @('copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5') -DisablePaging
    }

    New-HTMLSection -HeaderBackGroundColor '#990AE3' -HeaderText "Report Information" {
        New-HTMLPanel {
            New-HTMLList -Type Ordered {
                New-HTMLListItem -Text "Report generated on: $currentDateTime (UTC)"
                New-HTMLListItem -Text "Generated by: $currentUser"
                New-HTMLListItem -Text "Total records analyzed: $($healthcheckData.Count)"
            }
        }
    }
} -ShowHTML